# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170906_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_feedback',
            field=models.DateField(auto_now=True),
        ),
    ]
