# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20170908_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_feedback',
            field=models.CharField(max_length=250),
        ),
    ]
