# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_delete_moods'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mood_choices',
            field=models.CharField(choices=[(5, 'Happy!!'), (4, 'Glad :-)'), (3, 'Moderate'), (2, 'Sad :-('), (1, 'Mad !!')], default=5, max_length=1),
        ),
    ]
