# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_feedback_mood_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mood_choices',
            field=models.IntegerField(choices=[(5, 'Happy!!'), (4, 'Glad :-)'), (3, 'Moderate'), (2, 'Sad :-('), (1, 'Mad !!')], default=5),
        ),
    ]
