# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20171107_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_feedback',
        ),
    ]
